return {
  plugins = {
    "AstroNvim/astrocommunity",
    { import = "astrocommunity.colorscheme.nightfox-nvim" },
    { import = "astrocommunity.colorscheme.kanagawa-nvim" },
    { import = "astrocommunity.colorscheme.iceberg-vim" },
    { import = "astrocommunity.colorscheme.nightfox-nvim" },
    { import = "astrocommunity.pack.rust" },
    { import = "astrocommunity.pack.typescript" },
    { import = "astrocommunity.pack.python" },
    { import = "astrocommunity.pack.prisma" },
    { import = "astrocommunity.pack.lua" },
    { import = "astrocommunity.pack.markdown" },
    { import = "astrocommunity.pack.toml" },
    { import = "astrocommunity.pack.yaml" },
    { import = "astrocommunity.pack.docker" },
    { import = "astrocommunity.pack.terraform" },
    { import = "astrocommunity.pack.go" },
  },
  colorscheme = "iceberg",
}
